[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chapter-9"
version = "0.1"
dependencies = ["numpy"]

[tool.hatch.build.targets.wheel]
      packages = ["expressions"]